### ISSUE TITLE
SSL issue "unable to find valid certification path to requested target"

### ISSUE THREAD

**Issue by nicolas-g** [rundeck-plugins/pagerduty-notification#13]
Fresh installation of Rundeck : 

- Rundeck version 2.9.3-1
- Java 1.8.0_144 
- CentOS 7

I can make this plugin to work in any of the jobs.. have tried crating keys for both pagerDuty API v1 and v2.

**/var/log/rundekc/service.log** :
> ERROR NotificationService: Error sending notification: Notification{eventTrigger='onstart', type='PagerDutyNotification', content='{"subject":"${job.status} [${job.project}] \"${job.name}\" run by ${job.user} (#${job.execid}) [${job.href}]"}'}: class javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at com.rundeck.plugins.PagerDutyNotificationPlugin.triggerEvent(PagerDutyNotificationPlugin.groovy:98)
	at com.rundeck.plugins.PagerDutyNotificationPlugin.postNotification(PagerDutyNotificationPlugin.groovy:59)
	at rundeck.services.NotificationService.triggerPlugin(NotificationService.groovy:490)
	at rundeck.services.NotificationService$_triggerJobNotification_closure5.doCall(NotificationService.groovy:352)
	at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:147)
	at rundeck.services.NotificationService$_triggerJobNotification_closure1.doCall(NotificationService.groovy:89)
	at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:86)
	at rundeck.services.ExecutionService.executeAsyncBegin(ExecutionService.groovy:1063)
	at rundeck.quartzjobs.ExecutionJob.executeCommand(ExecutionJob.groovy:344)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:143)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:91)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:90)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	... 35 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	... 35 more

**Comment by fdevans** [comment]
Closing this thread due to age.  If there are still issues please upgrade Rundeck to a current version and let us know if there are still issues.
