### ISSUE TITLE
Error: groovy.lang.MissingMethodException: No signature of method

### ISSUE THREAD

**Issue by philippevidal80** [rundeck-plugins/pagerduty-notification#5]
Hello,

I'm running a 2.6.8 clustered Rundeck and try to make this notification work like it does on my 2.4.2 single Rundeck, but I raise this error each time i try to use it on the new version of Rundeck:

```
ERROR NotificationService: Error sending notification: Notification{eventTrigger='onsuccess', type='PagerDutyNotification', content='{"subject":"${job.status} [${job.project}] \"${job.name}\" run by ${job.user} (#${job.execid})"}'}: class groovy.lang.MissingMethodException: No signature of method: PagerDutyNotification$_run_closure1_closure6.triggerEvent() is applicable for argument types: (null, java.util.HashMap) values: [null, [service_key:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, subject:${job.status} [Text] "Job" run by ${job.user} (#39)]]
groovy.lang.MissingMethodException: No signature of method: PagerDutyNotification$_run_closure1_closure6.triggerEvent() is applicable for argument types: (null, java.util.HashMap) values: [null, [service_key:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, subject:${job.status} [Text] "Job" run by ${job.user} (#39)]]
	at PagerDutyNotification$_run_closure1_closure6.doCall(PagerDutyNotification:111)
	at com.dtolabs.rundeck.server.plugins.builder.ScriptNotificationPlugin.postNotification(ScriptNotificationPlugin.groovy:62)
	at rundeck.services.NotificationService.triggerPlugin(NotificationService.groovy:475)
	at rundeck.services.NotificationService$_triggerJobNotification_closure5.doCall(NotificationService.groovy:337)
	at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:146)
	at rundeck.services.NotificationService$_triggerJobNotification_closure1.doCall(NotificationService.groovy:88)
	at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:85)
	at rundeck.services.ExecutionService$_saveExecutionState_closure60.doCall(ExecutionService.groovy:2089)
	at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:1994)
	at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:480)
	at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:418)
	at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:490)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:146)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:74)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:73)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

Did i missed something ? I'm definitly not a developer...
But it seems that "executionData" has a value of NULL !?

Thanks for your help.

Regards,
Philippe

**Comment by philippevidal80** [comment]
Sorry I've not seen before but it's related to https://github.com/rundeck-plugins/pagerduty-notification/pull/4.

I changed the line as mentionned and restart rundeck service and it goes on. :)
