### ISSUE TITLE
Error sending notification

### ISSUE THREAD

**Issue by yzargari** [rundeck-plugins/pagerduty-notification#8]
Hello,
I'm trying the plugin to send pageduty notifications and it is failing for success and failure. As a test, I made the notification subject to be just a string with no variables.

I'm getting the below error in rundeck.log
Any assistance would be greatly appreciated.

> 2017-04-09 06:16:57,130 [quartzScheduler_Worker-32] ERROR grails.app.services.rundeck.services.NotificationService - Error sending notification: Notification{eventTrigger='onsuccess', type='PagerDutyNotification', content='{"subject":"TEST SUCCESS"}'}: class groovy.lang.MissingMethodException: No signature of method: PagerDutyNotification$_run_closure1_closure6.triggerEvent() is applicable for argument types: (null, java.util.HashMap) values: [null, [service_key:<OMITTED>, subject:TEST SUCCESS]]
groovy.lang.MissingMethodException: No signature of method: PagerDutyNotification$_run_closure1_closure6.triggerEvent() is applicable for argument types: (null, java.util.HashMap) values: [null, [service_key:<OMITTED>, subject:TEST SUCCESS]]
	at PagerDutyNotification$_run_closure1_closure6.doCall(PagerDutyNotification:123)
	at com.dtolabs.rundeck.server.plugins.builder.ScriptNotificationPlugin.postNotification(ScriptNotificationPlugin.groovy:62)
	at rundeck.services.NotificationService.triggerPlugin(NotificationService.groovy:471)
	at rundeck.services.NotificationService$_triggerJobNotification_closure5.doCall(NotificationService.groovy:333)
	at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:142)
	at rundeck.services.NotificationService$_triggerJobNotification_closure1.doCall(NotificationService.groovy:84)
	at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:81)
	at rundeck.services.ExecutionService$_saveExecutionState_closure59.doCall(ExecutionService.groovy:2041)
	at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:1946)
	at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:480)
	at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:418)
	at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:490)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:146)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:74)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:73)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

My understanding is that it fails to find the triggerEvent function because the parameters passed aren't as expected by the function (it expects two maps while a NULL and a map are passed). Is this correct? What might be the reason for the executionData to be NULL?

**Comment by gschueler** [comment]
hmm, the only thing I noticed is that the `onsuccess` handler code differs from the others:
https://github.com/rundeck-plugins/pagerduty-notification/blob/master/src/PagerDutyNotification.groovy#L122

I think it should look like this:

    onsuccess { Map executionData, Map configuration ->

**Comment by yzargari** [comment]
Thanks @gschueler 
I didn't get a chance to try it and managed to find a workaround. The plugin will definitely be useful for me in the future, so I'll let you know as soon as I get around to it.
